"""Creacion de la tabla curso

Revision ID: 904ce7bb3342
Revises: 
Create Date: 2026-03-18 23:32:36.238976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '904ce7bb3342'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curso',
    sa.Column('id_curso', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('instructor', sa.String(length=100), nullable=False),
    sa.Column('duracion', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id_curso')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('curso')
    # ### end Alembic commands ###
